version: '3.8'
services:

  traefik:
    image: traefik:v2.10

  mysql:
    hostname: mysql
    image: mysql:8.2

  meilisearch:
    hostname: meilisearch
    image: getmeili/meilisearch:v1.5
    environment:
      MEILI_NO_ANALYTICS: "true"

  redis:
    hostname: redis
    image: redis:7.2

  php:
    build:
      context: .
      target: base
    depends_on:
      - traefik
      - mysql
      - meilisearch
      - redis
